### ISSUE TITLE
Full URL not being included on AuthRequest RelayState parameter 

### ISSUE THREAD

**Issue by grobz** [jornane/mwSimpleSamlAuth#18]
Hello sir.

I am experiencing an issue regarding RelayState redirection with your extension. 

When opening a deeplink of my wiki, a SAML AuthRequest is redirected to my IdP. On that AuthRequest, the RelayState parameter does not include the full URL of the deeplink. Therefore, when the redirection comes back from the SSO server, the browswer ends up opening the wiki home URL, instead of the full URL I requested in the first place.

Is this something that can/should be fixed?

Please advise.

**Comment by jornane** [comment]
Hi

Can you give some more information? I can't reproduce this problem on any of the wiki's i'm running.

**Comment by jornane** [comment]
Worksforme.
