### ISSUE TITLE
main page unavailable after adding saml conf to LocalSettings.php

### ISSUE THREAD

**Issue by r2r200** [jornane/mwSimpleSamlAuth#24]
Hello!

I try to integrate Mediawiki with ADFS using SAML 2.0 and SimpleSamlAuth module.
I configured and tested SimpleSamlphp - it correctly returns right attributes.

Then I got a problem - after adding conf (require_once ....) to LocalSettings.php main page coming unavailable.

Could you help me? What do I need to edit?

Thanks.

**Comment by jornane** [comment]
What do you mean with "unavailable"? Do your web server logs have something?

**Comment by jornane** [comment]
Worksforme
