### ISSUE TITLE
Mediawiki.org extension page out of date

### ISSUE THREAD

**Issue by jamesmontalvo3** [jornane/mwSimpleSamlAuth#25]
The extension documentation page is out of date.

It recommends version 0.4. Should this be bumped to v0.6, or perhaps left blank and recommend to checkout the latest tag? Are there any other items which need update on this page?

https://www.mediawiki.org/wiki/Extension:SimpleSamlAuth

**Comment by jornane** [comment]
I've updated the page, thanks!
