### ISSUE TITLE
PasswordError for new user logging in

### ISSUE THREAD

**Issue by rglasnap** [jornane/mwSimpleSamlAuth#26]
I've got a new user who's unable to log in. I'm running MediaWiki 1.25.2 and the latest version you've got here. I made some minor modifications to my version, but it was only to not run setGroups if wgSamlGroupMap is NULL.

Anyway, part of the backtrace is pasted here, I think the issue here that setPassword->(NULL) . It look like by doing that you're preventing *any* logins, not just manual log ins.

/wiki PasswordError from line 2397 of mw25/w/includes/User.php: There was either an authentication database error or you are not allowed to update your external account.
Backtrace:
#0 mw25/w/extensions/SimpleSamlAuth/SimpleSamlAuth.class.php(442): User->setPassword(NULL)
#1 mw25/w/extensions/SimpleSamlAuth/SimpleSamlAuth.class.php(399): SimpleSamlAuth::updateUser(User, array)
#2 mw25/w/extensions/SimpleSamlAuth/SimpleSamlAuth.class.php(260): SimpleSamlAuth::loadUser(User, array)
#3 [internal function]: SimpleSamlAuth::hookLoadSession(User, NULL)

**Comment by jornane** [comment]
Hmm, looks like there is some additional password checking in MediaWiki 1.25. I'll look into it.

**Comment by jornane** [comment]
Looks like I should be using `setInternalPassword(NULL)` instead of `setPassword(NULL)`. Please try that as a hotfix while I do some more reading over the weekend.

**Comment by rglasnap** [comment]
I ended up rolling back to the previous version yesterday just to get it working again. I'll have to try that out on a dev-site (once I hunt down some more test users).

**Comment by jornane** [comment]
Was fixed in e509a1a1.
