### ISSUE TITLE
Login Case issue

### ISSUE THREAD

**Issue by Fraifrai** [jornane/mwSimpleSamlAuth#27]
Hello,

The standard case for mediawiki logins seems to be lower case except the first character so that installing the extension on an existing wiki, as the IdP Provides uppercase logins, we had to make such a conversion.

$attr[$wgSamlUsernameAttr] = array(ucfirst(strtolower(reset($attr[$wgSamlUsernameAttr]))));

Shouldn't it be a feature ?

**Comment by jornane** [comment]
Hmm, i'm not really sure. MediaWiki does support usernames in camel case form, I don't want to break that. On the other hand, I see your problem. I'm not really sure if this is something the extension should handle, or SimpleSamlPhp. I know about the [core:authproc_attributealter](https://simplesamlphp.org/docs/stable/core:authproc_attributealter) module, but i'm not sure that it will solve your problem.

**Comment by jornane** [comment]
If your IdP supplies you with uppercase usernames, this is a problem you would have with other SPs as well, so this is a problem that should be solved in SimpleSamlPHP. You can do this with the [core:authproc_php](https://simplesamlphp.org/docs/stable/core:authproc_php) module.

Add the following to your SimpleSamlPHP's config.php in the `authproc.sp` array.

```php
array(
    'class' => 'core:PHP',
    'code' => '$attributes["uid"] = array_map("strtolower", $attributes["uid"]);',
),
```

This is not an ideal solution, I have created [a ticket in the SimpleSamlPHP project](https://github.com/simplesamlphp/simplesamlphp/issues/328) for this.

**Comment by Fraifrai** [comment]
it works freat 

thanks
