### ISSUE TITLE
No logout link in mw with mwSimpleSamlAuth installed

### ISSUE THREAD

**Issue by worpweasel** [jornane/mwSimpleSamlAuth#32]
Hi,

I have mwSimpleSamlAuth and SimpleSamlphp installed and mostly working – clicking login in mw takes me to the proper InCommon login which progresses normally until I hit the final enter key. At this point I'm dropped back into mw without actually being logged in.
Seems like the saml data isn't being properly given to mw. What step am I missing?

Cheers,
Tim

**Comment by jornane** [comment]
Which version of MediaWiki are you using?

**Comment by worpweasel** [comment]
Jørn,

First let me apologize for my rather noobish “ticket”. Further research indicates that my issue is really the same as a number of other posts complaining about not being able to pass attributes from SimpleSAMLphp through SimplesamlAuth to MediaWiki. However, I’ve been unable to get any of the suggestions to work.

I’m running MediaWiki version 1.24.2, and SimpleSAMLphp version 1.14.8.

To anticipate another question, here is the SAML portion of my Localsettings.php:
##SAML settings
require_once "$IP/extensions/SimpleSamlAuth/SimpleSamlAuth.php";

// SAML_OPTIONAL // SAML_LOGIN_ONLY // SAML_REQUIRED //
$wgSamlRequirement = SAML_OPTIONAL;
// Should users be created if they don't exist in the database yet?
$wgSamlCreateUser = false;

// SAML attributes
$wgSamlUsernameAttr = 'uid';
$wgSamlRealnameAttr = 'cn';
$wgSamlMailAttr = 'mail';

// SimpleSamlPhp settings
$wgSamlSspRoot = '/var/simplesamlphp';
$wgSamlAuthSource = 'default-sp';
$wgSamlPostLogoutRedirect = NULL;

#SimpleSamlPhp is using phpsession so this shouldn't need uncommented.
#$wgSessionName = 'phpsession';

// Array: [MediaWiki group][SAML attribute name][SAML expected value]
// If the SAML assertion matches, the user is added to the MediaWiki group
$wgSamlGroupMap = array(
        'sysop' => array(
                'groups' => array('admin'),
        ),
);

Thank you very much for your time and effort helping me with this.

Cheers,
Tim

On Oct 20, 2016, at 5:43 AM, Jørn Åne <notifications@github.com<mailto:notifications@github.com>> wrote:


Which version of MediaWiki are you using?

**Comment by jornane** [comment]
This kind of issue is always related to MediaWiki and SimpleSamlPhp disagreeing on how to do sessions. This is especially a problem when both MediaWiki and SimpleSamlPhp use PHP's built-in session management system. I have used quite a lot of time to get this right, but of course there may still be bugs – it is a complicated problem after all. Other plugins may interfere, certain MediaWiki settings I haven't tested may do so too.

Please make sure you use the latest version of the plugin (0.7 at this time), I have noticed that there are guides out there recommending 0.4, which has some unfixed bugs.

For a quick fix, I would recommend letting SimpleSamlPhp use a different session handler, for example memcache. That solves the problem in most situations.

If it still doesn't work, make sure that your setup does not have any extra redirects. A typical example would be your MediaWiki being on http and SimpleSamlPhp on https, or different hostnames. Redirects typically remove sessions.

As a test, you could try the following. After [SimpleSamlAuth.class.php:70](https://github.com/jornane/mwSimpleSamlAuth/blob/v0.7/SimpleSamlAuth.class.php#L70), you can add the following line:
```php
self::$as->isAuthenticated();
```

This change will trigger SimpleSamlPhp's session-system earlier, which *should* not make any difference, but may help.

**Comment by worpweasel** [comment]
Executing a git clone vs downloading off mediwiki's site, I get:
----
Cloning into 'SimpleSamlAuth'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights and the repository exists.
----

**Comment by jornane** [comment]
Your output states:

```
Cloning into 'SimpleSamlAuth'...
Permission denied (publickey).
```

That means you use the SSH link, it requires an SSH key even for public repositores. This is not the link you got from the [MediaWiki site](https://www.mediawiki.org/wiki/Extension:SimpleSamlAuth), which is `https://github.com/jornane/mwSimpleSamlAuth.git`.

That being said, I hardly think that the issue tracker for a MediaWiki plugin is the place to ask for support on how to use GitHub. You should check out the [GitHub documentation](https://help.github.com/articles/error-permission-denied-publickey/) for that.

**Comment by worpweasel** [comment]
Problem resolved.
Set SimpleSamlAuth to use urn:oid numbers, set $wgSessionName = 'sql';, and set $wgSamlPostLogoutRedirect =  to a logout URL.
Set SimpleSAMLphp config.php to use 'sql' and of course, set up a mysql database for it to use.
Also, if you're behind an F5 or similar, you may need to set 'trusted.url.domains'

**Comment by jornane** [comment]
You should not need to set `$wgSessionName`, but it won't hurt either. Otherwise that sounds about right.
