### ISSUE TITLE
Azure AD to MediaWiki Issue: SimpleSAML_Error_NoState: NOSTATE 

### ISSUE THREAD

**Issue by carlneal** [jornane/mwSimpleSamlAuth#42]
I have configured SimpleSAMLPhp and verified it Authenticates here: https://{website}/simplesamlphp/www/module.php/core/authenticate.php

However when I try to login to the site, I'm redirected  to my Azure AD Login, then afterwards to a SimpleAuth page that states:

State information lost
State information lost, and no way to restart the request

Debug information

The debug information below may be of interest to the administrator / help desk:

SimpleSAML_Error_NoState: NOSTATE
Backtrace:
2 D:\home\site\wwwroot\simplesamlphp\lib\SimpleSAML\Auth\State.php:263 (SimpleSAML_Auth_State::loadState)
1 D:\home\site\wwwroot\simplesamlphp\modules\saml\www\sp\saml2-acs.php:78 (require)
0 D:\home\site\wwwroot\simplesamlphp\www\module.php:137 (N/A)

I'm using SimpleSAML 1.14.14 and Mediawiki 1.28.

How can I get around this issue?

**Comment by carlneal** [comment]
Below are my settings in LocalSettings.php

require_once "$IP/extensions/SimpleSamlAuth/SimpleSamlAuth.php";
// make sure that session storage matches to the one used in simplesaml most likely default PHPSESSID
$wgSessionName = "PHPSESSID";

// SAML_OPTIONAL // SAML_LOGIN_ONLY // SAML_REQUIRED //
$wgSamlRequirement = SAML_REQUIRED;
// Should users be created if they don't exist in the database yet?
$wgSamlCreateUser = true;
 
// SAML attributes
$wgSamlUsernameAttr = 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name';
$wgSamlRealnameAttr = 'http://schemas.microsoft.com/identity/claims/displayname';
$wgSamlMailAttr = 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name';
 
// SimpleSamlPhp settings
$wgSamlSspRoot = '/simplesamlphp';
$wgSamlAuthSource = 'default-sp';
$wgSamlPostLogoutRedirect = NULL;

**Comment by jornane** [comment]
Try to make SimpleSamlPhp use another session backend, for example memcache or SQL. I haven't seen the infamous NOSTATE error before with this extension, but it may very well be related to the warning that's in [README.md](https://github.com/jornane/mwSimpleSamlAuth/blob/master/README.md).

> **IMPORTANT** If you run MediaWiki 1.27 or newer, SimpleSamlPhp **MUST** be configured to use an alternative session handler.
> If this is not done, SAML authentication succeeds, but MediaWiki still shows that nobody is logged in.
> Please refer to [the SimpleSamlPhp website](//simplesamlphp.org/docs/stable/simplesamlphp-maintenance) on how to configure SimpleSamlPhp for session storage.

**Comment by carlneal** [comment]
I actually tried that before I posted and it didnt' work. But trying it again I made the following adjustments to the config.php file:

change store.type in config.php file from 'phpsession' to 'memcache'.

I also tried both with the following and without the following change: 'session.phpsession.cookiename' => from 'PHPSESSID' to'PHPSESSIDv2',

Both gave me an HTTP 500 error:
 
The website cannot display the page
 
  HTTP 500 
    
Most likely causes:
•The website is under maintenance.
•The website has a programming error.

**Comment by carlneal** [comment]
I also used sql as a session storage (store.type) and got the Http 500 error as well.

**Comment by jornane** [comment]
Error 500 means you should check your webserver logs.

**Comment by carlneal** [comment]
Thanks we can close this I just found another extension to use sorry I couldn't make this work.
